ДЗ Практика 2
itmogamedev/cpp pull request #10
Opened 2023-10-12 22:51 UTC by Georgy-Titov

2023-10-13 19:35 UTC, k-kondyukov requested changes

2023-10-13 19:35 UTC, k-kondyukov commented on TitovGK/HW1/1.1.cpp
> +	std::cout << (char) s1 << std::endl;
Зачем int к char приводите? Почему сразу не хранить в char?

2023-10-13 23:33 UTC, Georgy-Titov commented on TitovGK/HW1/1.1.cpp
> +	std::cout << (char) s1 << std::endl;
У меня были проблемы с выводом, пришлось придумать костыль. Как я понял проблема была в неявных преобразованиях, сейчас запушу исправленный вариант

2023-10-28 11:58 UTC, k-kondyukov approved these changes

2023-10-28 11:58 UTC, merged