1 и 2 Домашки
itmogamedev/cpp pull request #11
Opened 2023-10-13 09:48 UTC by Strizhov-Dmitry-Andreevich

2023-10-13 10:33 UTC, k-kondyukov requested changes

2023-10-13 10:33 UTC, k-kondyukov commented on StrizhovDA/HomeWook1/Task1.cpp
> +char a = 256+88; //88 в char это Х
Отступы потерялись

2023-10-13 20:22 UTC, k-kondyukov commented on StrizhovDA/HomeWook2/Task2.cpp
> +    std::cin >> n;
Предусмотрели, если пользователь введет отрицательное число?

2023-10-13 20:41 UTC, k-kondyukov requested changes

2023-10-13 20:41 UTC, k-kondyukov commented on StrizhovDA/HomeWook2/Task2.cpp
> +        std::cout << -;
Ошибка компиляции будет:
```
main.cpp: In function ‘int main()’:
main.cpp:15:21: error: expected primary-expression before ‘;’ token
   15 |       std::cout << -;
```

2023-10-13 20:46 UTC, Strizhov-Dmitry-Andreevich commented on StrizhovDA/HomeWook2/Task2.cpp
> +        std::cout << -;
ё моё что за приколы, я делаю '-' а он не сохранил, ВС просто с ума сошел

2023-10-18 14:34 UTC, k-kondyukov approved these changes

2023-10-18 14:34 UTC, merged