homework
itmogamedev/cpp pull request #15
Opened 2023-10-13 20:46 UTC by TimofeyZhuravlevEgorovich

2023-10-15 07:54 UTC, k-kondyukov requested changes

2023-10-15 07:54 UTC, k-kondyukov commented on ZhuravlevTE/HW1/zadanie1.cpp
> +    const char maxChar = 255;
Размерность char:
-128–127 по умолчанию От 0 до 255 при компиляции с помощью /J

Т.е. уже у вас тут будет переполнение, если вы компилировали при стандартных настройках :)

2023-10-15 07:54 UTC, k-kondyukov commented on ZhuravlevTE/HW2/zadanie1.cpp
> +    std::cin >> n;
А если пользователь введет отрицательное значение?

2023-10-15 07:54 UTC, k-kondyukov commented on ZhuravlevTE/HW2/zadanie2.cpp
> +	std::cin >> n;
И тут тоже что с отрицательными числами??

2023-10-15 11:53 UTC, TimofeyZhuravlevEgorovich commented
patch notes 15.10.2023:

Fixed a HW1/zadanie1.cpp; Now char overflowing works normal.
Negative numbers now converts to positive in case of HW2/zadanie1.cpp and HW2/zadanie2.cpp; In case of zadanie1.cpp, "-" adds in end of reversed negative number.

2023-11-08 07:46 UTC, k-kondyukov approved these changes

2023-11-08 07:46 UTC, merged