HW 1-2
itmogamedev/cpp pull request #20
Opened 2023-10-14 01:32 UTC by LyntiknaJAVA

2023-10-15 08:00 UTC, k-kondyukov requested changes

2023-10-15 08:00 UTC, k-kondyukov commented on DvornikovAS/HW2/Task1.cpp
> +    double* array = new double[size];
А зачем вы выделяете память через new?

2023-10-15 08:00 UTC, k-kondyukov commented on DvornikovAS/HW2/Task1.cpp
> +    //delete[] array; this thing frees memory, but it causes VS to crash, so I've commented it out.
А тут у вас утечка памяти будет :D

2023-10-15 08:00 UTC, k-kondyukov commented on DvornikovAS/HW2/Task2.cpp
> +        >> n;
Что будет при отрицательном n?

2023-10-20 12:57 UTC, LyntiknaJAVA commented on DvornikovAS/HW2/Task1.cpp
> +    double* array = new double[size];
Я выделяю память, чтобы пользователь мог сам ввести длину массива (по-другому в VS у меня не работает, он ругается на то, что невозможно создать массив)

2023-10-20 12:58 UTC, LyntiknaJAVA commented on DvornikovAS/HW2/Task1.cpp
> +    //delete[] array; this thing frees memory, but it causes VS to crash, so I've commented it out.
Я изначально оставил эту строку, но VS тоже ругается на неё

2023-10-20 13:12 UTC, LyntiknaJAVA commented on DvornikovAS/HW2/Task1.cpp
> +    double* array = new double[size];
Немного поясню: изначально я хотел сделать это задание с помощью массива (просто первая идея), но столкнулся с тем, что для массива значение должно быть константой. То есть нельзя просто с клавиатуры ввести значение n и сделать массив длиной n (ошибка в скриншоте). Поэтому я нашёл способ сначала выделить память, а потом удалить массив. Но и с удалением массива тоже всё пошло не так, VS ругается на его удаление и крашит консоль
![err 1](https://github.com/itmogamedev/cpp/assets/76556872/5d91f40b-fe05-4ead-9c61-614ef1a7d7f3)

2023-10-20 13:14 UTC, LyntiknaJAVA commented on DvornikovAS/HW2/Task1.cpp
> +    //delete[] array; this thing frees memory, but it causes VS to crash, so I've commented it out.
Вот как VS ругается на удаление массива в конце кода
![image](https://github.com/itmogamedev/cpp/assets/76556872/5f71fc19-3276-4f93-b6a0-9d4a67a76cc3)

2023-10-20 13:17 UTC, LyntiknaJAVA commented on DvornikovAS/HW2/Task2.cpp
> +        >> n;
Программа просто переврнёт число и оставит перед ним знак "-".
Нужно было сделать что-то другое?))

2024-03-11 20:10 UTC, closed without merging