First commit
itmogamedev/cpp pull request #23
Opened 2023-10-14 14:35 UTC by AlexandraBoyko

2023-10-15 08:04 UTC, k-kondyukov requested changes

2023-10-15 08:04 UTC, k-kondyukov commented on BoykoAK/Dz2-2.cpp
> +    std::cin >> input;
Что будет при input меньше 0?

2023-10-15 08:04 UTC, k-kondyukov commented on BoykoAK/dz1-1.cpp
> +	std::cout << "Perepolnenie po char: ";
Не пишите транслитом пожалуйста

2023-10-15 08:04 UTC, k-kondyukov commented on BoykoAK/dz1-2.cpp
> +	std::cin >> cifra;
cifra - у нас такое не пройдет ).
Только number :)

2023-10-24 19:18 UTC, AlexandraBoyko commented on BoykoAK/Dz2-2.cpp
> +    std::cin >> input;
Выведет минус и за ним цифры в обратном порядке. Или в задаче подразумевалось, что при input<0 минус нужно выводить в конце, после цифр?

2023-10-24 19:18 UTC, AlexandraBoyko commented on BoykoAK/dz1-1.cpp
> +	std::cout << "Perepolnenie po char: ";
Исправила

2023-10-24 19:18 UTC, AlexandraBoyko commented on BoykoAK/dz1-2.cpp
> +	std::cin >> cifra;
Исправила

2023-10-24 22:11 UTC, k-kondyukov commented on BoykoAK/Dz2-2.cpp
> +    std::cin >> input;
Тут все ок

2023-10-24 22:12 UTC, k-kondyukov approved these changes

2023-10-24 22:12 UTC, merged