Ht1 & Ht2
itmogamedev/cpp pull request #25
Opened 2023-10-14 18:08 UTC by TemirovArtem

Извиняюсь за столь позднюю отправку. Честно делал в срок, но самим git не занимался.

2023-10-15 07:57 UTC, k-kondyukov requested changes

2023-10-15 07:57 UTC, k-kondyukov commented on TemirovAT/HT 2/Fibonachi.cpp
> +		if (i == 1)
А можно вот так:
```
		if (i == 1 or i == 2)
		{
			std::cout << i-1 << endl;
		}
```

Вместо:
```
		if (i == 1)
		{
			std::cout << 0 << endl;
		}
		if (i == 2)
		{
			std::cout << 1 << endl;
		}
```

2023-10-15 07:57 UTC, k-kondyukov commented on TemirovAT/HT 2/Reverse.cpp
> +	std::cin >> N;
Что будет если пользователь введет отрицательное число?

2023-10-20 20:55 UTC, TemirovArtem reviewed
Changed

2023-10-20 20:58 UTC, TemirovArtem commented on TemirovAT/HT 2/Reverse.cpp
> +	std::cin >> N;
Выводило ноль. Теперь выводит нужное значение.

2023-10-20 21:02 UTC, TemirovArtem commented on TemirovAT/HT 2/Fibonachi.cpp
> +		if (i == 1)
Изменил.

2023-10-27 19:45 UTC, TemirovArtem commented on TemirovAT/HT 2/Reverse.cpp
> +	std::cin >> N;
@k-kondyukov

2024-03-12 22:12 UTC, closed without merging