1z
itmogamedev/cpp pull request #29
Opened 2023-10-20 21:56 UTC by AmirovZaur

2023-10-24 13:35 UTC, k-kondyukov requested changes

2023-10-24 13:35 UTC, k-kondyukov commented on AmirovZaur/P2Z1.cpp
> +    cout << "������� ���������� ��������� ���� ���������: ";
Кракозябры

2023-10-24 13:35 UTC, k-kondyukov commented on AmirovZaur/P2Z1.cpp
> +	int N, a = 0, b = 1;
Разные отступы

2023-10-24 13:35 UTC, k-kondyukov commented on AmirovZaur/P2Z2.cpp
> +    std::cout << "������� �����: ";
Кракозябры

2023-10-24 13:35 UTC, k-kondyukov commented on AmirovZaur/P2Z2.cpp
> +    std::cout << "����� � �������� �������� ����: " << reversedNumber << std::endl;
Кракозябры

2024-03-12 22:15 UTC, AmirovZaur reviewed
g

2024-03-12 22:16 UTC, closed without merging