Шейко Олег дз1
itmogamedev/cpp pull request #37
Opened 2024-02-28 16:11 UTC by olegsheyko

(честно, пытался убрать папку .idea, даже прописал её в гитигнор, но она так и не исчезла)

2024-02-29 07:27 UTC, k-kondyukov commented
Файлы можно удалить при добавлении коммита. Кроме того можно залить отдельный коммит только одним файлом

2024-02-29 07:27 UTC, k-kondyukov requested changes
.

2024-03-05 19:16 UTC, olegsheyko commented
> .

Здравствуйте, обновил. Проверьте, пожалуйста.

2024-03-06 06:41 UTC, k-kondyukov requested changes
Замечания

2024-03-06 06:41 UTC, k-kondyukov commented on sem2/SheykoOA_Homework/homework1/.gitignore
Какой-то гитигнор попал

2024-03-06 06:41 UTC, k-kondyukov commented on sem2/SheykoOA_Homework/homework1/.gitignore
Нам он тут не нужен

2024-03-06 06:41 UTC, k-kondyukov commented on sem2/SheykoOA_Homework/homework1/main.cpp
> +    Lambda predicate(symbol);
По заданию требовалось лямбда выражение.
Вы сделали предикат.

2024-03-06 18:49 UTC, olegsheyko commented
> Замечания

Хорошо, исправил. Проверьте, пожалуйста.

2024-03-16 18:11 UTC, k-kondyukov approved these changes
Approve

2024-03-16 18:12 UTC, merged