Create minihomework1.cpp
itmogamedev/cpp pull request #41
Opened 2024-03-07 15:29 UTC by Sofochk

Сделала алгоритмом из библиотеки algorithm с использованием внутри лямбда функции

2024-03-10 15:36 UTC, k-kondyukov requested changes

2024-03-10 15:36 UTC, k-kondyukov commented on sem2/SobolevaSD/minihomework1.cpp
> +using namespace std;
`using namespace std;`
Не принимаю код с этой строчкой.

2024-03-13 09:06 UTC, Sofochk commented on sem2/SobolevaSD/minihomework1.cpp
> +using namespace std;
Изменила

2024-03-16 17:56 UTC, k-kondyukov requested changes
Исправляйте

2024-03-16 17:56 UTC, k-kondyukov commented on sem2/SobolevaSD/minihomework1.cpp
> +﻿#include <iostream>
Не компилируется.
Не используйте преподавателя как компилятор.

2024-03-26 20:40 UTC, Sofochk commented
> Исправляйте
Исправила!

2024-04-17 11:08 UTC, k-kondyukov approved these changes

2024-04-17 11:08 UTC, merged