1
itmogamedev/cpp pull request #51
Opened 2024-03-12 16:56 UTC by A-661

2024-03-16 18:38 UTC, k-kondyukov requested changes

2024-03-16 18:38 UTC, k-kondyukov commented on sem2/Суворов Андрей/stl_lambda.cpp
> +    std::vector<std::string> stroki;
Транслит в имени переменных не принимаю

2024-03-20 17:39 UTC, A-661 commented on sem2/Суворов Андрей/stl_lambda.cpp
> +    std::vector<std::string> stroki;
исправил

2024-03-27 08:41 UTC, k-kondyukov requested changes
"Суворов Андрей" напишите по-английски, пожалуйста :)

2024-04-10 12:46 UTC, A-661 commented
всё сделал (>_<)

2024-04-21 07:05 UTC, k-kondyukov approved these changes

2024-04-21 07:05 UTC, merged