HW-2
itmogamedev/cpp pull request #6
Opened 2023-10-07 11:23 UTC by gh272b

О боги надеюсь я все верно сделал

2023-10-11 14:10 UTC, k-kondyukov requested changes

2023-10-11 14:10 UTC, k-kondyukov commented on KozhevnikovAV/ConsoleApplication18.cpp
> +    if (n == 0) {
А можно сделать короче:

```
    if (n == 0 or n == 1) {
        return n;
    }
```
Вместо:
```
    if (n == 0) {
            return 0;
    }
    if (n == 1) {
        return 1;
    }
```

2023-10-11 18:15 UTC, AlexKozhORmeatspeice commented on KozhevnikovAV/ConsoleApplication18.cpp
> +    if (n == 0) {
ой, кстати красивенько реально! по хорошему б еще сам алгоритм оптимизировать, чтобы он по веткам по одним и тем же веткам проходил, но как эт реализовать на плюсах не знаю к сожалению :(

2023-10-14 12:45 UTC, AlexKozhORmeatspeice commented
Вроде подправил все

2023-10-14 15:07 UTC, k-kondyukov requested changes

2023-10-14 15:07 UTC, k-kondyukov commented on KozhevnikovAV/ConsoleApplication18.cpp
> +    std::cin >> n;
Если пользователь введет отрицательный n, что тогда будет с программой ?)

2023-10-16 12:23 UTC, AlexKozhORmeatspeice commented on KozhevnikovAV/ConsoleApplication18.cpp
> +    std::cin >> n;
Бесконечная рекурсия будет. Подправил

2024-03-16 18:03 UTC, k-kondyukov approved these changes

2024-03-16 18:03 UTC, merged