miniHW Antonov
itmogamedev/cpp pull request #61
Opened 2024-03-12 20:26 UTC by vovaant-AK-VladimirAntonov

2024-03-16 19:07 UTC, k-kondyukov approved these changes
.

2024-03-16 19:10 UTC, k-kondyukov requested changes
Хотя нет. Исправьте название файла и локацию

2024-03-17 15:31 UTC, vovaant-AK-VladimirAntonov commented
Сделал

2024-04-21 07:18 UTC, k-kondyukov approved these changes

2024-04-21 07:18 UTC, merged