Kirichenko_hw
itmogamedev/cpp pull request #64
Opened 2024-03-12 21:36 UTC by AleksandraKirichenko

2024-03-16 19:13 UTC, k-kondyukov requested changes
Переименуйте русскоязычные файлы на английские

2024-03-16 21:46 UTC, AleksandraKirichenko commented
Исправила, проверьте, пожалуйста

2024-03-27 08:45 UTC, k-kondyukov requested changes
`bukva` - транслит, ругаюсь и не принимаю ^__^

2024-03-28 18:54 UTC, AleksandraKirichenko commented
Исправила

2024-04-21 07:21 UTC, k-kondyukov approved these changes

2024-04-21 07:21 UTC, merged