DvornikovArtem_miniHW3
itmogamedev/cpp pull request #90
Opened 2024-04-28 22:08 UTC by DvornikovArtem

2024-05-08 17:43 UTC, k-kondyukov requested changes

2024-05-08 17:43 UTC, k-kondyukov commented on sem2/DvornikovAS/minihomework1/minihomework1.cpp
> +    std::cout << "\x1b[34mEnter a symbol you wanna item start with: " << std::endl;
\x1b[34
Что ето?

2024-05-09 03:00 UTC, DvornikovArtem commented on sem2/DvornikovAS/minihomework1/minihomework1.cpp
> +    std::cout << "\x1b[34mEnter a symbol you wanna item start with: " << std::endl;
Это escape-последовательность, которая позволяет менять цвет текста в консоли C++ без использования <Windows.h>. Если нужно, могу их убрать.

2024-05-25 16:02 UTC, k-kondyukov approved these changes

2024-05-25 16:04 UTC, k-kondyukov approved these changes

2024-05-25 16:04 UTC, merged