MolushkinaAA HW3 + HW1, HW2
itmogamedev/cpp pull request #97
Opened 2024-05-01 20:18 UTC by AnnaMolushkina

2024-05-08 17:56 UTC, k-kondyukov requested changes
Вторую домашку нужно заливать весь проект целиком согласно ТЗ

2024-05-25 15:54 UTC, k-kondyukov requested changes

2024-05-25 15:54 UTC, k-kondyukov commented on sem2/MolushkinaAA/HW1/lyambda function.cpp
> +    //for (std::vector<std::string>::const_iterator i = my_vec.begin(); i != my_vec.end(); i++) //чтение вектора
Закоментированный код не принимаю

2024-05-25 16:01 UTC, AnnaMolushkina commented on sem2/MolushkinaAA/HW1/lyambda function.cpp
> +    //for (std::vector<std::string>::const_iterator i = my_vec.begin(); i != my_vec.end(); i++) //чтение вектора
Эта строка не нужна для работы программы

2024-05-29 13:30 UTC, k-kondyukov approved these changes

2024-05-29 13:31 UTC, merged